"""Default parameters for the single proposed-method demo."""

from __future__ import annotations

import numpy as np


def default_config() -> dict:
    """Return the default single-diagnostic XL-RIS configuration."""
    c0 = 299_792_458.0
    fc = 60.0e9
    wavelength = c0 / fc

    return {
        "seed": 20260526,
        "trials": 1,
        "SNR_dB": 20.0,
        "enable_global_vp": True,
        "stage2_mode": "none",
        "diagnostic_mode": "performance",
        "run_full_legacy_comparison": False,
        "verbose_stage2": False,
        "print_progress": True,
        "diagnostic_fast_problem_size": False,
        "diagnostic_fast_stage1_search": False,
        "stage2_adaptive": True,
        "stage2_rescue_type": "ris_only",
        "reliability_assignment_good": 1.0,
        "reliability_assignment_low": 0.3,
        "reliability_clock_good_ns": 0.1,
        "reliability_clock_bad_ns": 0.5,
        "reliability_ris_good": 0.3,
        "reliability_ris_bad": 0.7,
        "final_refinement_method": "global_exact_spherical_vp",
        "K": 3,
        "M_A": 16,
        "ris_shape": (64, 64),
        "N": 63,
        "P": 32,
        "T": 256,
        "c0": c0,
        "fc": fc,
        "wavelength": wavelength,
        "delta_f": 5.0e6,
        "delta_t_true": 5.0e-9,
        "p_B": np.array([0.0, 0.0, 1.0]),
        "p_u_true": np.array([1.25, 0.55, 0.75]),
        "ris_centers": np.array(
            [
                [4.20, -2.20, 1.05],
                [5.10, 2.10, 1.15],
                [4.80, 0.00, 1.25],
            ]
        ),
        "ue_bounds": np.array(
            [
                [0.30, 2.70],
                [-1.40, 1.50],
                [0.35, 1.45],
            ]
        ),
        "delta_t_bounds": np.array([0.0, 10.0e-9]),
        "stage1_delay_method": "aimdf_tls",
        "stage1_forward_backward": True,
        "stage1_tls": True,
        "stage1_factor_init": "hankel_coupled_ls",
        "stage1_factor_reg": 1.0e-10,
        "ris_search": {
            "range_bounds": (2.5, 6.5),
            "elev_bounds": (-0.45, 0.25),
            "az_bounds": (-np.pi, np.pi),
            "num_range": 15,
            "num_elev": 9,
            "num_az": 25,
            "stage2_num_range": 3,
            "stage2_num_elev": 3,
            "stage2_num_az": 5,
            "stage2_range_span": 0.45,
            "stage2_angle_span": 0.12,
            "num_lift_candidates": 4,
            "num_lift_steps": 4,
            "lambda_phys": 1.0e-2,
            "ris_pgd_step_scale": 0.5,
            "num_exact_refine_starts": 6,
            "projection_mode": "wesvp_ms",
            "use_qd_init": False,
            "qd_proxy_reg": 1.0e-6,
            "qd_proxy_max_rel_residual": 0.5,
            "qd_num_range": 41,
            "wesvp_max_iter": 100,
            "wesvp_ftol": 1.0e-12,
            "wesvp_gtol": 1.0e-8,
            "use_fresnel_warm_start": True,
        },
        "num_structured_iters": 2,
        "stage2_enable_evs": False,
        "stage2_enable_delay": False,
        "stage2_enable_ris": True,
        "stage2_guarded": True,
        "stage2_strict_accept_rel": 1.0e-6,
        "ris_min_relative_improvement": 5.0e-3,
        "stage2_damping_grid": (0.0, 0.125, 0.25, 0.5, 0.75, 1.0),
        "stage2_global_safeguard": True,
        "stage2_tol": 1.0e-5,
        "stage2_ris_weight_mode": "residual_diag",
        "stage2_ris_weight_floor_rel": 5.0e-2,
        "stage2_ris_weight_clip": (0.25, 4.0),
        "stage2_ris_weight_normalize": True,
        "delay_lambda": 1.0e-2,
        "delay_num_pgd_steps": 10,
        "delay_step_scale": 0.8,
        "delay_damping": 0.8,
        "delay_geometry_rho": 0.2,
        "assignment_clock_weight": 0.5,
        "assignment_clock_scale_s": 1.0e-9,
        "delay_refine_phase_span": 0.35,
        "delay_refine_phase_grid": 9,
        "vp_max_nfev": 10,
        "vp_max_iter": 10,
        "global_vp": {
            "solver": "least_squares",
            "max_iter": 80,
            "ftol": 1.0e-12,
            "gtol": 1.0e-8,
            "beta_reg": 0.0,
            "evs_mode": "legacy_or_full_polarization",
            "use_delay_prior": False,
            "delay_prior_weight": 1.0,
            "delay_prior_sigma_s": 2.0e-11,
            "use_weight": False,
            "use_multistart": False,
            "num_perturb_starts": 0,
            "position_perturb_std_m": 0.05,
            "clock_perturb_std_s": 1.0e-10,
            "use_trust_region": False,
            "position_trust_radius_m": 0.3,
            "clock_trust_radius_s": 3.0e-10,
            "objective_rollback_tolerance": 1.0e-12,
            "overwrite_factor_keys": False,
            "finite_difference_check": False,
        },
        "eps": 1.0e-10,
    }
